### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by deeeznuds** [OnixFlutterTeam/ml_card_scanner#1]
I want to try this plugin, but I can't because of failing of version solving.
Please update packages:
[camera](https://pub.dev/packages/camera), [firebase_core](https://pub.dev/packages/firebase_core), [flutter](https://api.flutter.dev/), [google_mlkit_text_recognition](https://pub.dev/packages/google_mlkit_text_recognition), [permission_handler](https://pub.dev/packages/permission_handler)

**Comment by OnixFlutterTeam** [comment]
dependencies updated in v0.0.4
