### ISSUE TITLE
Android build issue

### ISSUE THREAD

**Issue by nimr77** [OnixFlutterTeam/ml_card_scanner#14]
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: /Users/mac/.pub-cache/hosted/pub.dev/ml_card_scanner-0.2.0/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by Coloud1** [comment]
Hello, [nimr77](https://github.com/nimr77).

Thanks for finding the problem. In new 0.2.1 version everything should work correctly.
