### ISSUE TITLE
Scanning expiration date

### ISSUE THREAD

**Issue by WooSeokChung** [OnixFlutterTeam/ml_card_scanner#5]
I tried this plugin, but scanning expiration date always failed.
Would you please check if there is a problem?

**Comment by cozvtieg9** [comment]
Hi @WooSeokChung . I checked the expiration date recognition and made some fixes. 
Try it on version 0.0.6 (should be available on pub.dev soon)

**Comment by WooSeokChung** [comment]
Hi @cozvtieg9 .  I tried scanning expiration date, and it works fine. But unfortunately, the max resolution of the camera occurs a crash on my iphone 8.

**Comment by cozvtieg9** [comment]
@WooSeokChung I'll add a option to change resolution soon

**Comment by cozvtieg9** [comment]
@WooSeokChung 
version v0.0.7 uploaded. (should be available on pub.dev soon)
- added option to change camera resolution preset;

**Comment by WooSeokChung** [comment]
@cozvtieg9 Now it's working on my iphone. Thanks for the updates!
